### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by oxters168** [torokati44/ruffle-android#1]
Hey, I've been trying to get Flash running on android for a while through ruffle. I had a bit of luck getting the js version working through webview, but I'm not happy with some things. Then I ran into your project and it seems to be a much better version since it looks like you're running ruffle natively. I wanted to try it out for myself and started following your steps for the build process. Side-note I'm on Windows 10.

Here's what I've done so far:
I made sure I had the proper SDK and NDK in android studio. I installed rust. I then ran your first two commands `cargo install cargo-apk` and `rustup target add aarch64-linux-android`. The first command failed giving an error said `link.exe failed` or something like that. Turns out rust by default points to 32-bit binaries and running `rustup default stable-x86_64-pc-windows-gnu` fixes that. Then I set up the environment variables for `ANDROID_SDK_ROOT` and `ANDROID_NDK_ROOT` then I ran `cargo apk build --release`. I got an error which I noticed said something about armv7 so I switched up the target by using `cargo apk build --release --target aarch64-linux-android`. I got a different error this time looking for java. I downloaded OpenJDK 18 and point JAVA_HOME to it. This time it built and I got the two .so files and copied them over. I now ran `./gradlew build` but then ran into the error `unsupported class file major version 62`. I thought maybe using an older version of java might help fix that since some answers were saying upgrade gradle. So I got OpenJDK 17 and redid the build and deleted the old .so files and copied the new ones. This time I ran `./gradlew build` and it looked like it was working until I ran into another error.

```
> Task :ruffle:packageRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':ruffle:packageRelease' (type 'PackageApplication').
  - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.tasks.PackageApplication' property 'signingConfigData.signingConfigData.storeFile' specifies file 'C:\Users\oxter\Projects\AndroidStudio\ruffle-android\app\ruffle\androidkey.jks' which doesn't exist.
```

I'm not entirely sure what to do from here, I've opened the project now in android studio to try and mess around. I wanted to see if I could just generate my own key but couldn't find the option or at least not yet. I'll report back if I figure it out, but also any help/guidance would be appreciated. Thanks

**Comment by oxters168** [comment]
Turns out I made a stupid mistake and opened the project from ruffle-android rather than from app which you clearly state. But now I'm running into a different issue. It seems when the app tries to run it gets an error saying `couldn't find "libruffle_android.so"` even though I built that and another file in the previous step and placed them in jniLibs. I'll look into it and report back.

**Comment by torokati44** [comment]
Hi!

This is where `cargo-apk` should output the `.so` files (only the selected part is relevant at the bottom):
![image](https://user-images.githubusercontent.com/288816/162377418-be9d23f3-ab12-4f2b-bf1d-e4f21e3e296a.png)

And this is where they should be copied
![image](https://user-images.githubusercontent.com/288816/162377489-ab7dff24-27bf-4ec9-8180-94e0a0ad0fb6.png)

**Comment by oxters168** [comment]
Got it working, turns out the .so files need to be placed in a folder in jniLibs called arm64-v8a. Got to test a swf and it worked great, runs much much better than through the webview js version.

**Comment by torokati44** [comment]
Okay, glad it worked out!

> ... runs much much better than through the webview js version.

Yes, that was the motivation! :)

**Comment by oxters168** [comment]
@torokati44 seems we posted same time. I think what happened was because I set the target specifically for the cargo apk build, I didn't get the folders. Thanks for the help!

**Comment by torokati44** [comment]
Oh, I see. Didn't know that would change the directory structure...

**Comment by oxters168** [comment]
It was my fault to begin with, I should have added rustup target for armv7 as well so it wouldn't error out in the cargo apk build

**Comment by torokati44** [comment]
Well that's not in the README yet, updating it now... :)

**Comment by torokati44** [comment]
Oh BTW if all you wanted is to try it out, you could have downloaded one of the prebuilt `.apk`s from among the artifacts of the latest Actions run.
But this still isn't in the README either... :)

**Comment by oxters168** [comment]
Oh hahaha didn't realize I could do that. Well I kind of wanted to mess around with the code anyway, try and figure out how everything works. So this gave me a good headstart. Now I understand how NativeActivity works and how swf files are being loaded. I want to figure out how to get touch to work better and map a controller to keyboard input. I'm thinking it might need me to look into the ruffle source as well, but I hope not. I've never used rust before xD
