### ISSUE TITLE
fit screen size bug

### ISSUE THREAD

**Issue by soundsnow** [torokati44/ruffle-android#15]
[GROW_Island.zip](https://github.com/torokati44/ruffle-android/files/9660445/GROW_Island.zip)
![Screenshot_20220928-084141_Trebuchet](https://user-images.githubusercontent.com/109885044/192662508-1840a201-ab20-4186-b212-7b3d8c93ef46.png)
![Screenshot_20220928-084218_Trebuchet](https://user-images.githubusercontent.com/109885044/192662515-c3c817d4-4a93-4c10-af43-ed5619e14f04.png)

**Comment by torokati44** [comment]
I suppose this is the same build as in #16? In which case, this is a known issue unfortunately.

**Comment by soundsnow** [comment]
> I suppose this is the same build as in #16? In which case, this is a known issue unfortunately.

no, it's master build
no on-screen keyboard

**Comment by soundsnow** [comment]
portrait
I can't see both sides
landscape
I can't see the crater
