### ISSUE TITLE
covered game screen

### ISSUE THREAD

**Issue by soundsnow** [torokati44/ruffle-android#16]
[Black_Box.zip](https://github.com/torokati44/ruffle-android/files/9660974/Black_Box.zip)
[GROW_3.zip](https://github.com/torokati44/ruffle-android/files/9660976/GROW_3.zip)
![image79](https://user-images.githubusercontent.com/109885044/192674865-257cb46c-2951-46e6-a726-6e913bc1f415.png)
![image80](https://user-images.githubusercontent.com/109885044/192674870-c697bb86-6151-4990-9a5b-1f6ab0667831.png)
![Screenshot_20220928-102344_Trebuchet](https://user-images.githubusercontent.com/109885044/192674886-5bbec412-923b-41da-a853-887ae890e11a.png)

**Comment by torokati44** [comment]
What you're looking at, is an experimental build from a WIP topic branch - not one from `main`.
As such, all kinds of glitches, like the ones you shown above, are to be expected.
