### ISSUE TITLE
control methods

### ISSUE THREAD

**Issue by soundsnow** [torokati44/ruffle-android#17]
remove title bar ruffle, i know what's it

some games only require the mouse, so there is no need to display the virtual keyboard at this time

you need this option to play landscape horizontal typing games or some portrait vertical games
because the screen game has been covered by the keyboard
Virtual Keyboard Transparency
         {
            { "0%",   NULL },
            { "25%",  NULL },
            { "50%",  NULL },
            { "75%",  NULL },
            { "100%", NULL },
            { NULL, NULL },
         },
         "25%"

![image82](https://user-images.githubusercontent.com/109885044/192694312-7a3a624a-34c0-4ed6-a71d-355489937b81.png)

**Comment by soundsnow** [comment]
![image83](https://user-images.githubusercontent.com/109885044/192696195-42215d1b-702f-4146-824e-45a17e71cc93.png)

**Comment by torokati44** [comment]
Thank you for the ideas!

**Comment by soundsnow** [comment]
The on-screen fake mouse is the most commonly used and it should be placed in the upper right corner of the screen. Custom keyboard Gamepad is placed to the left of the fake mouse
You can also add options to let people customize the order of these controller icons

**Comment by soundsnow** [comment]
4 Arrows keys + Numpad
add: landscape Horizontal games

**Comment by soundsnow** [comment]
3 × 3 isn't good, 4 × 4 is better
for example
homebrew fighting games (street fighter)
Street Fighter II
6 buttons × 2 = 12 keys
newest homebrew Street Fighter
8 buttons × 2 = 16 keys
it's good to play any fighting games
4 × 4 = 16 keys
![image85](https://user-images.githubusercontent.com/109885044/192948968-65a72d8e-87c1-49aa-8f5d-e145ea6b57fc.png)

**Comment by soundsnow** [comment]
i forgot L3 and R3
![image87](https://user-images.githubusercontent.com/109885044/193002649-f50221a4-81d1-4da1-b5ca-2a82ae790309.png)
