### ISSUE TITLE
App gets stuck after loading

### ISSUE THREAD

**Issue by Sohil876** [torokati44/ruffle-android#49]
I tried playing kof wing v0.9 with this and it works flawlessly, so i try to play kof wing version 1.8-2 and it starts loading and gets stuck after 96% in a black screen i have to force stop app to try again, on some random try like once in like 6 tries game starts but crashes.

Game: King of fighters wing 1.8-2
Android version: 10
Phone: Samsung J6 2018
Arch: armv7

**Comment by torokati44** [comment]
This game feels quite resource-heavy, on my phone it crashed after a few seconds of playing.
So my guess is that the app simply runs out of memory and/or GPU resources...
If you are able to send the output of `adb logcat` when the crash happens on your end, that might help a bit to find the real cause...

**Comment by Sohil876** [comment]
I tried it again on latest version and it works just fine.
