### ISSUE TITLE
Failed to loading Cube Escape: Seasons

### ISSUE THREAD

**Issue by zhenghaoz** [torokati44/ruffle-android#53]
Thank you for creating such a fantastic project. It makes it possible to play classical Flash games on Android. However, when I tried to play Cube Escape: Seasons on my phone, the APP failed to load the game content.

<img width="400px" src="https://github.com/torokati44/ruffle-android/assets/9030120/ffc00542-8036-4b0d-a065-ec9a69e4465f">

Would you happen to know how to fix it?

PS: [cube-escape-seasons.zip](https://github.com/torokati44/ruffle-android/files/12503089/cube-escape-seasons.zip)

**Comment by torokati44** [comment]
> Thank you for creating such a fantastic project.

Aww, thank you! :blush: 

Also thank you for the report and the SWF! Unfortunately I have no idea why it doesn't play... :/ Seems like some games are just broken, like FPA World. Will try to keep in mind and find a fix sometime in the future!

**Comment by torokati44** [comment]
It seems that in your app, this game runs fine. Also, the player is properly destroyed, and the interface works afterwards.
Would you mind sharing the solutions for these that you found?

**Comment by torokati44** [comment]
Ooh, nice find!
Yes, PRs would be appreciated! ☺️

**Comment by torokati44** [comment]
> The key to is set the right URL.

Do you mean using `PlayerBuilder::with_spoofed_url`?

**Comment by zhenghaozzz** [comment]
https://github.com/torokati44/ruffle-android/blob/717184643c698cc2504038de4e8a0ce973397497/native/src/lib.rs#L234

Replace `"".to_string()` with the file path :D

**Comment by torokati44** [comment]
Ah, that one, right! ^^'
Turns out, for this specific game, just setting it to `"file://movie.swf".to_string()` was sufficient.
Thank you for sharing your solution!
If you were to stumble upon any similar fixes in the future, it would be awesome if you could share those too - even if just described in an issue, and not as a PR.
