### ISSUE TITLE
Do not display the text.

### ISSUE THREAD

**Issue by pingni9527** [torokati44/ruffle-android#58]
Can run normally.However, the text of the story and the display text of the button are not displayed.
I don't know if this is my problem or something.
But there is no denying that this software is really good.

**Comment by torokati44** [comment]
> But there is no denying that this software is really good.

Aww thank you! ☺️

> However, the text of the story and the display text of the button are not displayed.

You forgot to mention what game is this in. Most probably it's just due to some missing or buggy functionality in Ruffle itself.

**Comment by pingni9527** [comment]
it's a swf The game of files.
game can run normally, but it doesn't display the text.

**Comment by pingni9527** [comment]
I don't if this kind of game will make you feel disgusted.
because This game is an adult game.
![Screenshot_2023-10-24-20-06-17-56_ca928a15f04f98a9481dd3c405174be0](https://github.com/torokati44/ruffle-android/assets/148868787/fa4b1833-c276-4195-98ad-57ea0beeec41)
Just like this.There is no text at all.

**Comment by pingni9527** [comment]
> > 但不可否认，这个软件真的很好。
> 
> 噢，谢谢！☺️
> 
> > 但是，不显示故事的文本和按钮的显示文本。
> 
> 你忘了提到这是什么游戏。很可能只是由于 Ruffle 本身中的一些缺失或错误功能。

Just like this.There is no text at all.

**Comment by pingni9527** [comment]
> > But there is no denying that this software is really good.
> 
> Aww thank you! ☺️
> 
> > However, the text of the story and the display text of the button are not displayed.
> 
> You forgot to mention what game is this in. Most probably it's just due to some missing or buggy functionality in Ruffle itself.

Just like this.There is no text at all.

**Comment by torokati44** [comment]
Alright, thanks for the info!

Turns out, one half of the missing text was an Android-specific thing, which is now fixed in the just released version.

The other half is still missing, as that is a general Ruffle error. That is still to be investigated further...

**Comment by SladkiyTort** [comment]
Bro is playing "Crimson Keep". Such a giga chad.

**Comment by torokati44** [comment]
The remaining missing text is no longer specific to Android, moving to the main Ruffle repo:
https://github.com/ruffle-rs/ruffle/issues/14234
